PyCaret Model Example

In [7]:
#load data
import pandas as pd

#Load data
dataset = pd.read_csv(r'C:\Users\owner\Desktop\direct_marketing.csv')

dataset.head()

,ID,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,DM_category
0,100,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,4
1,101,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,11
2,102,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,1
3,103,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,2
4,104,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,4

In [3]:
#create unseen data for Tableau
data = dataset.sample(frac=0.95, random_state=786).reset_index(drop=True)
data_unseen = dataset.drop(data.index).reset_index(drop=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (60800, 12)
Unseen Data For Predictions: (3200, 12)

In [4]:
#pycaret setup
from pycaret.classification import *
clf = setup(data, target = 'visit', session_id=562, ignore_features=['ID'], silent = True)

Setup Succesfully Completed!

In [5]:
#create model
nb = create_model('nb')

      Accuracy     AUC  Recall   Prec.      F1   Kappa
0       0.7655  0.6296  0.2540  0.2304  0.2416  0.1033
1       0.7636  0.6306  0.2552  0.2289  0.2413  0.1018
2       0.7657  0.6220  0.2584  0.2334  0.2453  0.1070
3       0.7570  0.6056  0.2297  0.2072  0.2179  0.0745
4       0.7592  0.6009  0.2185  0.2039  0.2109  0.0690
5       0.7629  0.6212  0.2265  0.2132  0.2196  0.0800
6       0.7585  0.6076  0.2281  0.2082  0.2177  0.0752
7       0.7674  0.6182  0.2648  0.2388  0.2511  0.1139
8       0.7646  0.6058  0.2504  0.2279  0.2386  0.0997
9       0.7448  0.5960  0.2316  0.1933  0.2108  0.0600
Mean    0.7609  0.6137  0.2417  0.2185  0.2295  0.0885
SD      0.0063  0.0115  0.0156  0.0144  0.0147  0.0177

In [6]:
#finalize model (use all data to train)
nb_final = finalize_model(nb)

#save model and transformation pipeline
save_model(nb_final, 'C:/Users/owner/Desktop/nb_direct')

Transformation Pipeline and Model Succesfully Saved